fix+docs: sets EOS as padding token; updated default config; deleted extra quantization docs (#288)
## Description
- Added existence check for padding token, sets EOS as padding token if
none.
- Added "target_modules" to default config as that's required by some
models, I put the one [recommended for
OPT](https://github.com/huggingface/peft/blob/39ef2546d5d9b8f5f8a7016ec10657887a867041/src/peft/utils/other.py#L220)
- Deleted redundant quantization docs
- Changed `model = model.cpu()` to `model = model.to("cpu")`

## Motivation
Finetuning Llama without it resulted in this:
```
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as pad_token (tokenizer.pad_token = tokenizer.eos_token e.g.) or add a new pad token via tokenizer.add_special_tokens({'pad_token': '[PAD]'}).
```

The `model.to("cpu")` change prevents `CUDA OUT OF MEMORY` while
finetuning `meta-llama/Llama-3.1-8B-Instruct` on a single A6000 GPU with
[this
dataset](https://huggingface.co/datasets/zhonglongbao/amadeus_makisekurisu_processed/viewer/default/train?row=0).
I used default configs, and added `target_modules=[q_proj, v_proj]` to
the lora config as required.

I used this command for finetuning if you'd like to replicate this:
`sllm-cli deploy --model meta-llama/Llama-3.1-8B-Instruct --backend
transformers; sllm-cli fine-tuning --base-model
meta-llama/Llama-3.1-8B-Instruct --config
sllm/cli/default_ft_config.json`

## Type of Change
- [X] Bug fix
- [ ] New feature
- [ ] Breaking change
- [X] Documentation update

## Checklist
- [X] I have read the
[CONTRIBUTION](https://github.com/ServerlessLLM/ServerlessLLM/blob/main/CONTRIBUTING.md)
guide.
- [ ] I have updated the tests (if applicable).
- [ ] I have updated the documentation (if applicable).

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>